# Configuration for the Multi-Agent Support System

# AWS Bedrock Configuration for Claude
aws:
  access_key_id: "${AWS_ACCESS_KEY_ID}"
  secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
  region: "${AWS_REGION:-us-east-1}"
  model: "${AWS_BEDROCK_MODEL:-anthropic.claude-3-5-sonnet-20240620-v1:0}"
  temperature: 0.1
  max_tokens: 1000

# Agent Configuration
agents:
  supervisor:
    name: "Supervisor Agent"
    description: "Routes queries to IT or Finance specialists"

  it_agent:
    name: "IT Support Agent"
    description: "Handles IT-related queries and troubleshooting"

  finance_agent:
    name: "Finance Support Agent"
    description: "Handles finance-related queries and calculations"

  evaluator_agent:
    name: "Evaluator Agent"
    description: "Evaluates and refines specialist responses for clarity and relevance"

# Tool Configuration
tools:
  web_search:
    enabled: true
    timeout: 30
    max_results: 5

  file_reader:
    enabled: true
    max_file_size: 1048576  # 1MB
    allowed_extensions: [".txt", ".md", ".pdf", ".doc", ".docx"]

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/agent_system.log"

# Validation Configuration
validation:
  max_query_length: 1000
  min_query_length: 5
  allowed_characters: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 .!?@#$%^&*()_+-=[]{}|;':\",./<>?`~"

# Sample Documents Path
documents:
  it_docs_path: "docs/it"
  finance_docs_path: "docs/finance"
